language: python
python: 3.5
install: 
  - pip install -Ur requirements.txt
script: py.test organon/t
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJJUNJ2O6I3TQGOVA
  secret_access_key:
    secure: o6hEKMCm/t05PB44Jlhpt1cW9ULOr976zQFq8HoODrMA0FjySo8OWUmxhNOEXAtJNGWvB4UIuKMzCRclFJYGZu6p+0L4beWI9UMOvbMGcklcNq53TGdK5BtCr6uBd9izgwfhd9GbTCKgANlu+bManMoM1gii4SNyRPTXE23T7AOQQj4899EdZN5LJ0im0RFRgSgsAcgu3nM3xKJZERoHH3hWCaydb9e9cNZjka8rDhDZwvvCCM29yTy+eZmqJTo/9I17cNwMYtuzEWwQNz87JwxPQNREkscfvGyyreMacdHD63xpRAfK44v7wzFwRxaW3avqZ4WUbh/kgRG019YxvwAizcAUvdzVEQ7v7boiKG/0Au5GFnSzg2pOMat1lJG65NYGfpcJBzv/jwzMncIKzHeC5KdpLQ8bLqLILNzoSTi1SYzIkH4aiSDVDwXvHeyDzQ6ed07EBPnJna28S5oDcaPDnhKWR3h86NYeh4W1gpfjovKsx6gZ/lBIuyZt2LPN12g7in7atoOzpossei6mARudI3RzrHZyIOSkPnFtZARdsGLMDgKmmcg4ilbW1x3yJCLGOpuFKRhuUHydSx59klY2B8B3ljdHMcQcJMdCNBWfnpg2eb3J3b0FlS4qLiDX3wm6z27Gz4fGxTeYpXs+704j6d2ctpXq654G+/5le/Q=
  region: eu-central-1
  app: mindgraph
  env: mindgraph-dev2
  bucket_name: elasticbeanstalk-eu-central-1-572297945351
  on:
    repo: horoshenkih/mind-graph
